export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_PRIVATE_POSTS = "GET_PRIVATE_POSTS";
export const CLEAR_PRIVATE_POSTS = "CLEAR_PRIVATE_POSTs";
